[tool.poetry]
name = "microweaver"
version = "0.1.0"
description = "This is a framework for ESP32 microntroller for IoT projects"
authors = ["Sydel Palinlin <sydel.palinlin@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
paho-mqtt = "^1.6.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2"
pytest-mock = "^3.12.0"
pytest-asyncio = "^1.1.0"
pytest-cov = "^7.1.0"
mpy-cross-multi = "^2.0.0"
autoflake8 = "^0.4.1"
flake8 = "^7.0.0"
black = "^23.12.1"
isort = "^5.13.2"
bandit = "^1.7.6"
typer = "^0.27.1"
pyserial = "^3.5"
esptool = "^5.3.1"
tox = "^4.11.4"

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88

[tool.coverage.run]
source = ["."]
omit = [
    "tests/*",
    "dist/*",
    "backup/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
